package com.sbu.taskhandler.model;
// Generated Dec 10, 2019 12:56:25 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ParentTask generated by hbm2java
 */
@Entity
@Table(name = "parent_task", catalog = "fsd_assignments")
public class ParentTask implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2012725623121440945L;
	private Integer parentId;
	private String parentTask;
	private Set<Task> tasks = new HashSet<Task>(0);

	public ParentTask() {
	}
	
	public ParentTask(int id) {
		this.parentId = id;
	}

	public ParentTask(String parentTask) {
		this.parentTask = parentTask;
	}

	public ParentTask(String parentTask, Set<Task> tasks) {
		this.parentTask = parentTask;
		this.tasks = tasks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "parent_id", unique = true, nullable = false)
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "parent_task", nullable = false, length = 300)
	public String getParentTask() {
		return this.parentTask;
	}

	public void setParentTask(String parentTask) {
		this.parentTask = parentTask;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parentTask")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

}
